
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend-deployment
  labels:
    app: demo-backend
spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo-backend
          template:
            metadata:
              labels:
                app: demo-backend
                spec:
                  containers:
                    - name: demo-backend
                      image: __IMAGE__
                      ports:
                        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend-service
spec:
  selector:
    app: demo-backend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
