spring:
   datasource:
        url: ${DB_URL:jdbc:postgresql://postgres.example.com:5432/sampledb}
             username: ${DB_USER:postgres}
                  password: ${DB_PASSWORD:password}
                     jpa:
                          hibernate:
                                 ddl-auto: none
                                      show-sql: false
                                      server:
                                         port: 8080
                                         management:
                                            endpoints:
                                                 web:
                                                        exposure:
                                                                 include: health,info
