name: CI-CD to AKS

on:

  push:

    branches: ["main"]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code

        uses: actions/checkout@v4

      - name: Login to Azure

        uses: azure/login@v2

        with:

          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & Push Backend

        run: |

          az acr login --name ${{ secrets.ACR_NAME }}

          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./backend

          docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

      - name: Build & Push Frontend

        run: |

          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./frontend

          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Set AKS Context

        run: |

          az aks get-credentials --resource-group ${{ secrets.AKS_RG }} \

                                --name ${{ secrets.AKS_CLUSTER }} --overwrite-existing

      - name: Deploy with Helm

        run: |

          helm upgrade --install sample-app ./helm \

            --namespace dev --create-namespace
Azure Container Registry | Microsoft Azure
Store images for all types of container deployments and OCI artifacts, using Azure Container Registry.
 